### ISSUE TITLE
[TODO]: v.4.0.0

### ISSUE THREAD

**Issue by retraigo** [retraigo/fortuna#23]
- [x] Remove `history`.
- [ ] ~Add `tiers` back to support `featuring` items.~
- [x] Write better examples in README.md.
- [x] Remove extra features (features already provided by `Machine`) from `LimitedMachine`.
